# Generated by Django 3.0.3 on 2020-04-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='reemplazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), related_name='reemplazo', to='scg_app.Empleado'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='empleado',
            field=models.ForeignKey(on_delete=models.SET(''), related_name='empleado', to='scg_app.Empleado'),
        ),
        migrations.AlterField(
            model_name='reemplazo',
            name='clase',
            field=models.ForeignKey(on_delete=models.SET(''), related_name='clase_relat', to='scg_app.Clase'),
        ),
        migrations.AlterField(
            model_name='reemplazo',
            name='empleado_reemplazante',
            field=models.ForeignKey(on_delete=models.SET(''), related_name='emple_relat', to='scg_app.Empleado'),
        ),
    ]
