# Generated by Django 3.0.3 on 2020-04-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0002_auto_20200403_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoAusencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Motivo de Ausencia',
                'verbose_name_plural': 'Motivos de Ausencia',
                'get_latest_by': 'nombre',
            },
        ),
    ]
