# Generated by Django 3.0.3 on 2020-04-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0003_motivoausencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='ausencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), related_name='ausencia', to='scg_app.MotivoAusencia'),
        ),
        migrations.AlterField(
            model_name='ausencia',
            name='clase',
            field=models.ForeignKey(on_delete=models.SET(''), related_name='related_clase', to='scg_app.Clase'),
        ),
    ]
