# Generated by Django 3.0.3 on 2020-04-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0004_auto_20200404_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivoausencia',
            name='genera_pago',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
