# Generated by Django 3.0.3 on 2020-04-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0005_motivoausencia_genera_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='confirmada',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
