# Generated by Django 3.0.3 on 2020-04-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0006_clase_confirmada'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcaje',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BloqueDePresencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin', models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), related_name='fin', to='scg_app.Marcaje')),
                ('inicio', models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), related_name='inicio', to='scg_app.Marcaje')),
            ],
        ),
    ]
