# Generated by Django 3.0.3 on 2020-04-06 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0007_auto_20200405_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquedepresencia',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scg_app.Empleado'),
        ),
    ]
