# Generated by Django 3.0.3 on 2020-04-06 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0008_bloquedepresencia_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloquedepresencia',
            old_name='inicio',
            new_name='entrada',
        ),
        migrations.RenameField(
            model_name='bloquedepresencia',
            old_name='fin',
            new_name='salida',
        ),
        migrations.AddField(
            model_name='bloquedepresencia',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
