# Generated by Django 3.0.3 on 2020-04-06 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0009_auto_20200406_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloquedepresencia',
            old_name='salida',
            new_name='fin',
        ),
        migrations.RenameField(
            model_name='bloquedepresencia',
            old_name='entrada',
            new_name='inicio',
        ),
    ]
