# Generated by Django 3.0.3 on 2020-04-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0014_auto_20200408_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('Lun', 'Lunes'), ('Mar', 'Martes'), ('Mie', 'Miércoles'), ('Jue', 'Jueves'), ('Vie', 'Viernes'), ('Sab', 'Sábado'), ('Dom', 'Domingo')], max_length=9),
        ),
        migrations.AlterField(
            model_name='recurrencia',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('Lun', 'Lunes'), ('Mar', 'Martes'), ('Mie', 'Miércoles'), ('Jue', 'Jueves'), ('Vie', 'Viernes'), ('Sab', 'Sábado'), ('Dom', 'Domingo')], max_length=9),
        ),
    ]
