# Generated by Django 3.0.3 on 2020-04-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0017_auto_20200408_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miércoles'), ('3', 'Jueves'), ('4', 'Viernes'), ('5', 'Sábado'), ('6', 'Domingo')], max_length=9),
        ),
        migrations.AlterField(
            model_name='recurrencia',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miércoles'), ('3', 'Jueves'), ('4', 'Viernes'), ('5', 'Sábado'), ('6', 'Domingo')], max_length=9),
        ),
    ]
