# Generated by Django 3.0.3 on 2020-04-10 22:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0018_auto_20200408_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldo',
            name='mes',
            field=models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], default='01', help_text='Mes para el que desea sumar el saldo', max_length=2),
        ),
        migrations.AddField(
            model_name='saldo',
            name='saldo_asignado',
            field=models.PositiveIntegerField(default=0, help_text='Mes para el que desea sumar el saldo', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scg_app.Actividad'),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Mes para el que desea sumar el saldo', max_digits=5),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scg_app.Sede'),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='year',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040')], default='2020', help_text='Año', max_length=4),
        ),
    ]
