# Generated by Django 3.0.3 on 2020-04-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0021_auto_20200411_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='estado',
            field=models.CharField(blank=True, choices=[('0', 'Pendiente'), ('1', 'Realizada Normalmente'), ('2', 'Realizada por Reemplazo'), ('3', 'No Realizada por Ausencia'), ('4', 'No Realizada por Feriado'), ('5', 'Cancelada')], default='Pendiente', max_length=1, null=True),
        ),
    ]
