# Generated by Django 3.0.3 on 2020-04-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0023_auto_20200414_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='comentario',
            field=models.CharField(blank=True, help_text='Aclaraciones varias', max_length=1000),
        ),
        migrations.AlterField(
            model_name='clase',
            name='estado',
            field=models.CharField(blank=True, choices=[('0', 'Pendiente'), ('1', 'Realizada'), ('2', 'Reemplazado'), ('3', 'Ausencia'), ('4', 'Feriado'), ('5', 'Cancelada')], default='0', max_length=1, null=True),
        ),
    ]
