# Generated by Django 3.0.3 on 2020-04-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0024_auto_20200416_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='parent',
        ),
    ]
