# Generated by Django 3.0.3 on 2020-04-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0025_remove_clase_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='clases/', verbose_name='Adjunto'),
        ),
    ]
