# Generated by Django 3.0.3 on 2020-04-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0026_clase_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scg_app.GrupoActividad'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.CharField(blank=True, max_length=30, null=True)),
                ('clases', models.ManyToManyField(to='scg_app.Clase')),
            ],
        ),
    ]
