# Generated by Django 3.0.3 on 2020-04-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0027_auto_20200421_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='adjunto',
        ),
    ]
