# Generated by Django 3.0.3 on 2020-04-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0028_remove_clase_adjunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='coment',
        ),
        migrations.AddField(
            model_name='certificado',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Archivo'),
        ),
    ]
