# Generated by Django 3.0.3 on 2020-04-21 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0029_auto_20200421_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motivo', to='scg_app.MotivoAusencia'),
        ),
    ]
