# Generated by Django 3.0.3 on 2020-04-23 17:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0031_modeltest'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencia',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miércoles'), ('3', 'Jueves'), ('4', 'Viernes'), ('5', 'Sábado'), ('6', 'Domingo')], max_length=13, null=True),
        ),
    ]
