# Generated by Django 3.0.3 on 2020-04-23 18:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0032_recurrencia_weekdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrencia',
            name='dia_semana',
        ),
        migrations.AlterField(
            model_name='recurrencia',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miércoles'), ('3', 'Jueves'), ('4', 'Viernes'), ('5', 'Sábado'), ('6', 'Domingo')], max_length=13, null=True, verbose_name='Días de la semana'),
        ),
    ]
