# Generated by Django 3.0.3 on 2020-04-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0033_auto_20200423_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelTest',
        ),
    ]
