# Generated by Django 3.0.3 on 2020-04-24 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0034_delete_modeltest'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='id_netTime',
            field=models.PositiveIntegerField(default=0, help_text='Para matchear marcajes e importaciones', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
