# Generated by Django 3.0.3 on 2020-04-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0036_auto_20200424_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='liquidacion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipo',
        ),
    ]
