# Generated by Django 3.0.3 on 2020-04-24 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0038_auto_20200424_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scg_app.TipoLiquidacion'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scg_app.TipoContrato'),
        ),
    ]
