# Generated by Django 2.2 on 2020-04-29 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0041_auto_20200429_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivoausencia',
            name='id_netTime',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
