# Generated by Django 2.2 on 2020-04-29 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0042_motivoausencia_id_nettime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivoausencia',
            name='id_netTime',
            field=models.PositiveIntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
