# Generated by Django 2.2 on 2020-05-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0044_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='locked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
