# Generated by Django 2.2 on 2020-05-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0045_clase_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcaje',
            name='locked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
