# Generated by Django 2.2 on 2020-05-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0046_marcaje_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='abs_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
