# Generated by Django 2.2 on 2020-05-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0048_auto_20200507_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='locked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
