# Generated by Django 2.2 on 2020-05-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0051_historicalsaldo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSaldo',
        ),
    ]
