# Generated by Django 2.2 on 2020-05-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0053_userextend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtend',
        ),
    ]
