# Generated by Django 2.2 on 2020-05-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0054_delete_userextend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
