# Generated by Django 2.2 on 2020-05-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0057_auto_20200514_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'get_latest_by': 'id', 'ordering': ['-fecha'], 'permissions': [('confirm_classes', 'Can confirm classes')], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
    ]
