# Generated by Django 2.2 on 2020-05-14 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0058_auto_20200514_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'get_latest_by': 'id', 'ordering': ['-fecha'], 'permissions': [('confirm_classes', 'Can confirm classes'), ('absence_management', 'Can manage absence'), ('asign_replacement', 'Can assign replacements')], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
    ]
