# Generated by Django 2.2 on 2020-05-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0059_auto_20200514_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='parent_recurrencia',
            new_name='recurrencia',
        ),
    ]
