# Generated by Django 2.2 on 2020-05-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0060_auto_20200526_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='horas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
