# Generated by Django 2.2 on 2020-05-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0061_clase_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='monto_hora',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
