# Generated by Django 2.2 on 2020-05-27 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0062_auto_20200526_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scg_app.GrupoActividad'),
        ),
        migrations.AlterField(
            model_name='bloquedepresencia',
            name='fin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin', to='scg_app.Marcaje'),
        ),
        migrations.AlterField(
            model_name='bloquedepresencia',
            name='inicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inicio', to='scg_app.Marcaje'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scg_app.Actividad'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='ausencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausencia', to='scg_app.MotivoAusencia'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to='scg_app.Empleado'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='horas',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='reemplazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazo', to='scg_app.Empleado'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scg_app.Sede'),
        ),
        migrations.AlterField(
            model_name='marcaje',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scg_app.Empleado'),
        ),
        migrations.AlterField(
            model_name='recurrencia',
            name='actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scg_app.Actividad'),
        ),
        migrations.AlterField(
            model_name='recurrencia',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scg_app.Empleado'),
        ),
        migrations.AlterField(
            model_name='recurrencia',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scg_app.Sede'),
        ),
    ]
