# Generated by Django 2.2 on 2020-05-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0063_auto_20200527_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='horas',
            field=models.FloatField(default=0.0),
        ),
    ]
