# Generated by Django 2.2 on 2020-05-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0065_auto_20200529_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivoausencia',
            name='requiere_certificado',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
