# Generated by Django 2.2 on 2020-05-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0066_motivoausencia_requiere_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoactividad',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
