# Generated by Django 2.2 on 2020-06-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0068_grupoactividad_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='file_url',
        ),
    ]
