# Generated by Django 2.2 on 2020-06-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0070_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
