# Generated by Django 2.2 on 2020-06-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0071_comentario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='accion',
            field=models.CharField(blank=True, choices=[('gestion_ausencia', 'Gestión Ausencia'), ('gestion_reemplazo', 'Gestión Reemplazo'), ('confirmacion', 'Confirmación'), ('edicion', 'Edición'), ('cancelacion', 'Cancelación')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='locked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
