# Generated by Django 2.2 on 2020-06-02 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scg_app', '0072_auto_20200602_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='object_id',
        ),
        migrations.CreateModel(
            name='GrupoComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scg_app.Comentario')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
        ),
    ]
