# Generated by Django 2.2 on 2020-06-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0073_auto_20200602_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'get_latest_by': 'nombre', 'ordering': ['nombre'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='bloquedepresencia',
            options={'get_latest_by': '-fecha', 'ordering': ['-fecha', '-inicio'], 'permissions': [('recalculate_blocks', 'Can recalculate blocks of a specific day')], 'verbose_name': 'Bloque de presencia', 'verbose_name_plural': 'Bloques de presencia'},
        ),
        migrations.AlterModelOptions(
            name='certificado',
            options={'get_latest_by': 'locked', 'ordering': ['locked'], 'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterModelOptions(
            name='clase',
            options={'get_latest_by': '-fecha', 'ordering': ['-fecha'], 'permissions': [('confirm_classes', 'Can confirm classes'), ('absence_management', 'Can manage absence'), ('asign_replacement', 'Can assign replacements')], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'get_latest_by': '-fecha', 'ordering': ['-fecha'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'get_latest_by': 'dni', 'ordering': ['dni', 'apellido', 'nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='escala',
            options={'get_latest_by': 'nombre', 'ordering': ['nombre'], 'verbose_name': 'Escala', 'verbose_name_plural': 'Escalas'},
        ),
        migrations.AlterModelOptions(
            name='grupoactividad',
            options={'get_latest_by': 'nombre', 'ordering': ['nombre'], 'verbose_name': 'Grupo de Actividad', 'verbose_name_plural': 'Grupos de Actividad'},
        ),
        migrations.AlterModelOptions(
            name='grupocomentario',
            options={'get_latest_by': '-fecha', 'ordering': ['-fecha'], 'verbose_name': 'Grupo de comentarios', 'verbose_name_plural': 'Grupos de comentarios'},
        ),
        migrations.AlterModelOptions(
            name='marcaje',
            options={'get_latest_by': '-fecha', 'ordering': ['-fecha', 'hora'], 'verbose_name': 'Marcaje', 'verbose_name_plural': 'Marcajes'},
        ),
        migrations.AlterModelOptions(
            name='motivoausencia',
            options={'get_latest_by': 'nombre', 'ordering': ['nombre'], 'verbose_name': 'Motivo de Ausencia', 'verbose_name_plural': 'Motivos de Ausencia'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'get_latest_by': '-desde', 'ordering': ['-desde'], 'verbose_name': 'Periodo', 'verbose_name_plural': 'Periodos'},
        ),
        migrations.AlterModelOptions(
            name='recurrencia',
            options={'get_latest_by': '-fecha_desde', 'ordering': ['-fecha_desde', '-fecha_hasta'], 'verbose_name': 'Recurrencia', 'verbose_name_plural': 'Recurrencias'},
        ),
        migrations.AlterModelOptions(
            name='saldo',
            options={'get_latest_by': '-desde', 'ordering': ['-desde', '-hasta'], 'verbose_name': 'Saldo', 'verbose_name_plural': 'Saldos'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'get_latest_by': 'nombre', 'ordering': ['nombre'], 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.AlterModelOptions(
            name='tipoliquidacion',
            options={'get_latest_by': 'nombre', 'ordering': ['nombre'], 'verbose_name': 'Tipo de liquidación', 'verbose_name_plural': 'Tipos de liquidación'},
        ),
        migrations.AddField(
            model_name='grupocomentario',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
