# Generated by Django 2.2 on 2020-06-03 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0076_auto_20200603_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupocomentario',
            name='comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scg_app.Comentario'),
        ),
        migrations.AlterField(
            model_name='grupocomentario',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
