# Generated by Django 2.2 on 2020-06-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0077_auto_20200603_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupocomentario',
            options={'get_latest_by': '-comentario__fecha', 'ordering': ['-comentario__fecha', '-comentario__hora'], 'verbose_name': 'Grupo de comentarios', 'verbose_name_plural': 'Grupos de comentarios'},
        ),
        migrations.RemoveField(
            model_name='grupocomentario',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='grupocomentario',
            name='hora',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='accion',
            field=models.CharField(blank=True, choices=[('gestion_ausencia', 'Gestión de Ausencia'), ('gestion_reemplazo', 'Gestión de Reemplazo'), ('confirmacion', 'Confirmación'), ('edicion', 'Edición de Clase'), ('cancelacion', 'Cancelación'), ('comentario', 'Comentario')], max_length=50, null=True),
        ),
    ]
