# Generated by Django 2.2 on 2020-06-16 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0079_auto_20200612_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcaje',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='liquidaciones/', verbose_name='Archivo')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodo', to='scg_app.Periodo')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo', to='scg_app.TipoLiquidacion')),
            ],
            options={
                'verbose_name': 'Liquidacion',
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-periodo__fecha', 'tipo__nombre'],
                'get_latest_by': 'id',
            },
        ),
    ]
