# Generated by Django 2.2 on 2020-06-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0081_auto_20200616_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scg_app.Periodo'),
        ),
    ]
