# Generated by Django 2.2 on 2020-06-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0083_customscript'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomScript',
        ),
    ]
