# Generated by Django 2.2 on 2020-06-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0085_auto_20200617_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nro_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='legajo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
