# Generated by Django 2.2 on 2020-06-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0086_auto_20200617_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='convenio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
