# Generated by Django 2.2 on 2020-06-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0087_empleado_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='horas_diurnas',
            field=models.FloatField(default=0.0),
        ),
    ]
