# Generated by Django 2.2 on 2020-06-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0089_auto_20200622_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='horas_nocturnas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='clase',
            name='horas_diurnas',
            field=models.FloatField(default=0.0),
        ),
    ]
