# Generated by Django 2.2 on 2020-06-22 21:10

from django.db import migrations
import python_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0091_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='source',
            field=python_field.fields.PythonCodeField(blank=True, null=True),
        ),
    ]
