# Generated by Django 2.2 on 2020-06-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0092_script_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='source',
        ),
    ]
