# Generated by Django 2.2 on 2020-06-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0093_remove_script_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tipo', models.CharField(blank=True, choices=[('Real', 'Real'), ('Virtual', 'Virtual')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ['nombre', 'tipo'],
                'get_latest_by': 'nombre',
            },
        ),
    ]
