# Generated by Django 2.2 on 2020-06-24 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scg_app', '0094_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencia',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scg_app.Lugar'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Real', 'Real'), ('Virtual', 'Virtual')], default=('Real', 'Real'), max_length=50, null=True),
        ),
    ]
