"""
Django settings for scg project. 

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y=yxaf=l5p)+ogu1d3n2tn59$z(+%z)##uql@*pe5i^dhzmc7%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    #django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #terceros
    'multiselectfield',
    'report_builder',

    #propias
    'scg_app',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#for user messages
MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'
MESSAGE_TAGS = {message_constants.ERROR: 'danger'}  #fpr bootstrap style

ROOT_URLCONF = 'scg.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scg.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'#'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


#media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR),'media_uploads')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    #'/var/www/static/',
]
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR),'statics_pub')

### reporting ###
#REPORT_BUILDER_ASYNC_REPORT = True
REPORT_BUILDER_INCLUDE = [
    'user', 
    'scg_app.clase', 'scg_app.empleado', 'scg_app.actividad', 'scg_app.escala',
    'scg_app.grupoactividad', 'scg_app.marcaje', 'scg_app.motivoausencia',
    'scg_app.recurrencia', 'scg_app.saldo', 'scg_app.sede', 'scg_app.tipocontrato',
    'scg_app.tipoliquidacion', 'scg_app.bloquedepresencia', 'scg_app.certificado',
] # Allow only the model user to be accessed
#REPORT_BUILDER_FRONTEND = False


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/logout/?next=/'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' #para testeo de recuperacion de passwords, borrar despues!

#  SCG_APP specifics
SERVER_URL = "http://192.168.1.104:8091/webservice?"

MINS_TOLERACIA = 15

DIA_SEMANA_CHOICES = (
        ("0", "Lunes"), 
        ("1", "Martes"), 
        ("2", "Miércoles"), 
        ("3", "Jueves"), 
        ("4", "Viernes"), 
        ("5", "Sábado"), 
        ("6", "Domingo"), 
    )

ESTADOS_CHOICES = (
        ("0", "Pendiente"),
        ("1", "Realizada"), 
        ("2", "Reemplazado"), 
        ("3", "Ausencia"), 
        ("4", "Feriado"),
         
        ("5", "Cancelada"), # keep last
    )

PERIODOS_CHOICES = (
        ("1", "16/01 al 15/02"), 
        ("2", "16/02 al 15/03"), 
        ("3", "16/03 al 15/04"), 
        ("4", "16/04 al 15/05"), 
        ("5", "16/05 al 15/06"), 
        ("6", "16/06 al 15/07"), 
        ("7", "16/07 al 15/08"), 
        ("8", "16/08 al 15/09"), 
        ("9", "16/09 al 15/10"), 
        ("10", "16/10 al 15/11"), 
        ("11", "16/11 al 15/12"), 
        ("12", "16/12 al 15/01"), 
    )

MESES_CHOICES = (
    ("01", "Enero"),
    ("02", "Febrero"),
    ("03", "Marzo"),
    ("04", "Abril"),
    ("05", "Mayo"),
    ("06", "Junio"),
    ("07", "Julio"),
    ("08", "Agosto"),
    ("09", "Septiembre"),
    ("10", "Octubre"),
    ("11", "Noviembre"),
    ("12", "Diciembre"),
)

PRESENCIA_CHOICES = (
        ("No Realizada", "No Realizada"),

        ("Realizada", "Realizada"), #keep last
    )

ANOS_CHOICES = tuple(zip([str(a) for a in range(2020, 2041)], [str(b) for b in range(2020, 2041)]))
