# Generated by Django 2.2 on 2020-05-21 15:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True, unique=True)),
                ('tags', models.TextField(blank=True, max_length=200, null=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
