# Generated by Django 2.2 on 2020-05-21 19:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
