# Generated by Django 2.2 on 2020-05-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20200521_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
