# Generated by Django 2.2 on 2020-06-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_help_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
